<a href="https://colab.research.google.com/github/Mithun-J/DSA_B13_Casestudy-1/blob/main/DataAcquisition_B13_by_Mithun.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# TASK 1
import pandas as pd

population = pd.read_csv("/content/drive/MyDrive/DSAB13/Colab Notebooks/Dataset/case study dataset/population.csv")

print("First 5 rows:")
display(population.head())
print("")

print("Shape:")
print(population.shape)
print("")

print("Data Types:")
print(population.dtypes)

First 5 rows:

         country  population
0  United States   331002651
1          China  1411778724
2          India  1380004385
3          Japan   125836021
4        Germany    83240525

Shape:
(25, 2)

Data Types:
country       object
population     int64
dtype: object

In [ ]:
# TASK 2
gdp = pd.read_excel("/content/drive/MyDrive/DSAB13/Colab Notebooks/Dataset/case study dataset/gdp.xlsx")

print("First 5 rows:")
display(gdp.head())

print("Column name:")
print(gdp.columns)

print("Data Types:")
print(gdp.dtypes)

First 5 rows:

         Country       GDP
0  United States  30500000
1          China  19230000
2          India   4187000
3          Japan   4180000
4        Germany   4744000

Column name:
Index(['Country', 'GDP'], dtype='object')
Data Types:
Country    object
GDP         int64
dtype: object

In [ ]:
# Task 3

internet_users = pd.read_json("/content/drive/MyDrive/DSAB13/Colab Notebooks/Dataset/case study dataset/internet_users.json")

df = pd.DataFrame(internet_users)
display(df)

print("First 5 rows:")

display(internet_users.head())

print("Shape:")

print(internet_users.shape)

print("Data Types:")

print(internet_users.dtypes)

           country  internet_users
0    United States       312000000
1            China      1080000000
2            India       850000000
3            Japan       118000000
4          Germany        79000000
5   United Kingdom        66000000
6           France        62000000
7            Italy        56000000
8           Canada        36000000
9        Australia        24000000
10          Brazil       181000000
11          Russia       125000000
12     South Korea        50000000
13           Spain        44000000
14          Mexico       102000000
15       Indonesia       212000000
16    Saudi Arabia        34000000
17          Turkey        69000000
18    South Africa        43000000
19       Argentina        41000000
20     Netherlands        17000000
21     Switzerland         8500000
22          Sweden        10100000
23          Norway         5300000
24       Singapore         5600000

First 5 rows:

         country  internet_users
0  United States       312000000
1          China      1080000000
2          India       850000000
3          Japan       118000000
4        Germany        79000000

Shape:
(25, 2)
Data Types:
country           object
internet_users     int64
dtype: object

In [ ]:
# Task 4
literacy_rate = pd.read_xml("/content/drive/MyDrive/DSAB13/Colab Notebooks/Dataset/case study dataset/literacy_rate.xml")

print("First 5 rows:")
display(literacy_rate.head())
print("")

print("Shape:")
print(literacy_rate.shape)
print("")

print("Data Types:")
print(literacy_rate.dtypes)

First 5 rows:

            name  literacy_rate
0  United States           99.0
1          China           97.2
2          India           77.7
3          Japan           99.0
4        Germany           99.0

Shape:
(25, 2)

Data Types:
name              object
literacy_rate    float64
dtype: object

In [ ]:
# Task 5

datasets = {
    "Population": population,
    "GDP": gdp,
    "Internet Users": internet_users,
    "Literacy Rate": literacy_rate
}

for name, data in datasets.items():

    display(name)

    print("Shape:")
    display(data.shape)
    print("")

    print("Column Names:")
    display(data.columns.tolist())
    print("")

    print("Data Types:")
    display(data.dtypes)
    print("")

    print("Missing Values:")
    display(data.isnull().sum())
    print("")

    print("Duplicate Records:")
    display(data.duplicated().sum())
    print("")

    print("-" * 50)
    print("")

'Population'

Shape:

(25, 2)

Column Names:

['country', 'population']

Data Types:

country       object
population     int64
dtype: object

Missing Values:

country       0
population    0
dtype: int64

Duplicate Records:

np.int64(0)

--------------------------------------------------

'GDP'

Shape:

(25, 2)

Column Names:

['Country', 'GDP']

Data Types:

Country    object
GDP         int64
dtype: object

Missing Values:

Country    0
GDP        0
dtype: int64

Duplicate Records:

np.int64(0)

--------------------------------------------------

'Internet Users'

Shape:

(25, 2)

Column Names:

['country', 'internet_users']

Data Types:

country           object
internet_users     int64
dtype: object

Missing Values:

country           0
internet_users    0
dtype: int64

Duplicate Records:

np.int64(0)

--------------------------------------------------

'Literacy Rate'

Shape:

(25, 2)

Column Names:

['name', 'literacy_rate']

Data Types:

name              object
literacy_rate    float64
dtype: object

Missing Values:

name             0
literacy_rate    0
dtype: int64

Duplicate Records:

np.int64(0)

--------------------------------------------------

In [ ]:
# Task 6

gdp.rename(columns={"Country": "country"}, inplace=True)

internet_users.rename(columns={"Country": "country"}, inplace=True)

literacy_rate.rename(columns={"name": "country"}, inplace=True)

print("Population:")
display(population.columns)
print("")

print("GDP:")
display(gdp.columns)
print("")

print("Internet Users:")
display(internet_users.columns)
print("")

print("Literacy Rate:")
display(literacy_rate.columns)

Population:

Index(['country', 'population'], dtype='object')

GDP:

Index(['country', 'GDP'], dtype='object')

Internet Users:

Index(['country', 'internet_users'], dtype='object')

Literacy Rate:

Index(['country', 'literacy_rate'], dtype='object')

In [ ]:
# Task 7

population["population"] = pd.to_numeric(population["population"])
gdp["GDP"] = pd.to_numeric(gdp["GDP"])
internet_users["internet_users"] = pd.to_numeric(internet_users["internet_users"])
literacy_rate["literacy_rate"] = pd.to_numeric(literacy_rate["literacy_rate"])


print("Population Data Types:")
display(population.dtypes)

print("GDP Data Types:")
display(gdp.dtypes)

print("Internet Users Data Types:")
display(internet_users.dtypes)

print("Literacy Rate Data Types:")
display(literacy_rate.dtypes)

Population Data Types:

country       object
population     int64
dtype: object

GDP Data Types:

country    object
GDP         int64
dtype: object

Internet Users Data Types:

country           object
internet_users     int64
dtype: object

Literacy Rate Data Types:

country           object
literacy_rate    float64
dtype: object

In [ ]:
# Task 8

merged_data = population.merge(
    gdp,
    on="country",
    how="inner"
)

merged_data = merged_data.merge(
    internet_users,
    on="country",
    how="inner"
)

merged_data = merged_data.merge(
    literacy_rate,
    on="country",
    how="inner"
)

display(merged_data)

           country  population       GDP  internet_users  literacy_rate
0    United States   331002651  30500000       312000000           99.0
1            China  1411778724  19230000      1080000000           97.2
2            India  1380004385   4187000       850000000           77.7
3            Japan   125836021   4180000       118000000           99.0
4          Germany    83240525   4744000        79000000           99.0
5   United Kingdom    67886011   3839000        66000000           99.0
6           France    65273511   3211000        62000000           99.0
7            Italy    60461826   2420000        56000000           99.0
8           Canada    38005238   2250000        36000000           99.0
9        Australia    25687041   1880000        24000000           99.0
10          Brazil   212559417   2330000       181000000           93.2
11          Russia   145934462   2200000       125000000           99.7
12     South Korea    51780579   1800000        50000000           98.8
13           Spain    46754778   1710000        44000000           98.6
14          Mexico   128932753   1810000       102000000           95.4
15       Indonesia   273523615   1500000       212000000           96.0
16    Saudi Arabia    34813871   1100000        34000000           97.3
17          Turkey    84339067   1350000        69000000           96.7
18    South Africa    59308690    410000        43000000           95.0
19       Argentina    45195774    640000        41000000           99.1
20     Netherlands    17441139   1150000        17000000           99.0
21     Switzerland     8654622    940000         8500000           99.0
22          Sweden    10353442    650000        10100000           99.0
23          Norway     5421241    580000         5300000          100.0
24       Singapore     5850342    530000         5600000           97.5

In [ ]:
# Task 9

merged_data["Internet Penetration (%)"] = (
    merged_data["internet_users"] / merged_data["population"] * 100
).round(2)

merged_data["GDP Per Capita"] = (
    merged_data["GDP"] / merged_data["population"]
).round(2)

display(merged_data)

,country,population,GDP,internet_users,literacy_rate,Internet Penetration (%),GDP Per Capita
0,United States,331002651,30500000,312000000,99.0,94.26,0.09
1,China,1411778724,19230000,1080000000,97.2,76.50,0.01
2,India,1380004385,4187000,850000000,77.7,61.59,0.00
3,Japan,125836021,4180000,118000000,99.0,93.77,0.03
4,Germany,83240525,4744000,79000000,99.0,94.91,0.06
5,United Kingdom,67886011,3839000,66000000,99.0,97.22,0.06
6,France,65273511,3211000,62000000,99.0,94.98,0.05
7,Italy,60461826,2420000,56000000,99.0,92.62,0.04
8,Canada,38005238,2250000,36000000,99.0,94.72,0.06
9,Australia,25687041,1880000,24000000,99.0,93.43,0.07
10,Brazil,212559417,2330000,181000000,93.2,85.15,0.01
11,Russia,145934462,2200000,125000000,99.7,85.65,0.02
12,South Korea,51780579,1800000,50000000,98.8,96.56,0.03
13,Spain,46754778,1710000,44000000,98.6,94.11,0.04
14,Mexico,128932753,1810000,102000000,95.4,79.11,0.01
15,Indonesia,273523615,1500000,212000000,96.0,77.51,0.01
16,Saudi Arabia,34813871,1100000,34000000,97.3,97.66,0.03
17,Turkey,84339067,1350000,69000000,96.7,81.81,0.02
18,South Africa,59308690,410000,43000000,95.0,72.50,0.01
19,Argentina,45195774,640000,41000000,99.1,90.72,0.01
20,Netherlands,17441139,1150000,17000000,99.0,97.47,0.07
21,Switzerland,8654622,940000,8500000,99.0,98.21,0.11
22,Sweden,10353442,650000,10100000,99.0,97.55,0.06
23,Norway,5421241,580000,5300000,100.0,97.76,0.11
24,Singapore,5850342,530000,5600000,97.5,95.72,0.09

In [ ]:
# Task 10

import sqlite3

connection = sqlite3.connect("country_statistics.db")

merged_data.to_sql(
    "country_statistics",
    connection,
    if_exists="replace",
    index=False
)

display("Database and table created successfully.")

'Database and table created successfully.'

In [ ]:
# Task 11

query = "SELECT * FROM country_statistics LIMIT 5"

first_five = pd.read_sql_query(query, connection)

display(first_five)

,country,population,GDP,internet_users,literacy_rate,Internet Penetration (%),GDP Per Capita
0,United States,331002651,30500000,312000000,99.0,94.26,0.09
1,China,1411778724,19230000,1080000000,97.2,76.50,0.01
2,India,1380004385,4187000,850000000,77.7,61.59,0.00
3,Japan,125836021,4180000,118000000,99.0,93.77,0.03
4,Germany,83240525,4744000,79000000,99.0,94.91,0.06

In [ ]:
# Part E - Question 1

top_5_gdp = merged_data.sort_values(
    by="GDP",
    ascending=False
).head(5)

display(top_5_gdp[["country", "GDP"]])

         country       GDP
0  United States  30500000
1          China  19230000
4        Germany   4744000
2          India   4187000
3          Japan   4180000

In [ ]:
# Part E - Question 2

top_5_population = merged_data.sort_values(
    by="population",
    ascending=False
).head(5)

display(top_5_population[["country", "population"]])

          country  population
1           China  1411778724
2           India  1380004385
0   United States   331002651
15      Indonesia   273523615
10         Brazil   212559417

In [ ]:
# Part E - Question 3

average_literacy = merged_data["literacy_rate"].mean()

display(average_literacy)

np.float64(97.248)

In [ ]:
# Part E - Question 4

literacy_above_90 = merged_data[
    merged_data["literacy_rate"] > 90
]

display(literacy_above_90[["country", "literacy_rate"]])

           country  literacy_rate
0    United States           99.0
1            China           97.2
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

In [ ]:
# Part E - Question 5

internet_above_70 = merged_data[
    merged_data["Internet Penetration (%)"] > 70
]

display(
    internet_above_70[
        ["country", "Internet Penetration (%)"]
    ]
)

           country  Internet Penetration (%)
0    United States                     94.26
1            China                     76.50
3            Japan                     93.77
4          Germany                     94.91
5   United Kingdom                     97.22
6           France                     94.98
7            Italy                     92.62
8           Canada                     94.72
9        Australia                     93.43
10          Brazil                     85.15
11          Russia                     85.65
12     South Korea                     96.56
13           Spain                     94.11
14          Mexico                     79.11
15       Indonesia                     77.51
16    Saudi Arabia                     97.66
17          Turkey                     81.81
18    South Africa                     72.50
19       Argentina                     90.72
20     Netherlands                     97.47
21     Switzerland                     98.21
22          Sweden                     97.55
23          Norway                     97.76
24       Singapore                     95.72

In [ ]:
# Part E - Question 6

top_5_gdp_per_capita = merged_data.sort_values(
    by="GDP Per Capita",
    ascending=False
).head(5)

display(
    top_5_gdp_per_capita[
        ["country", "GDP Per Capita"]
    ]
)

          country  GDP Per Capita
21    Switzerland            0.11
23         Norway            0.11
24      Singapore            0.09
0   United States            0.09
9       Australia            0.07

In [ ]:
# Part E - Question 7

total_population = merged_data["population"].sum()

display(total_population)

np.int64(4720039725)

In [ ]:
# Part E - Question 8

average_internet_penetration = merged_data[
    "Internet Penetration (%)"
].mean()

display(average_internet_penetration)

np.float64(89.6596)

In [ ]:
# Part E - Question 9

highest_internet_users = merged_data.loc[
    merged_data["internet_users"].idxmax()
]

display(
    highest_internet_users[
        ["country", "internet_users"]
    ]
)

country                China
internet_users    1080000000
Name: 1, dtype: object

In [ ]:
# Part E - Question 10

correlation = merged_data[
    "literacy_rate"
].corr(
    merged_data["Internet Penetration (%)"]
)

display(correlation)

np.float64(0.77279756813985)

In [ ]:
# Part F - Question 11

query = """
SELECT country, GDP
FROM country_statistics
ORDER BY GDP DESC
LIMIT 5
"""

result = pd.read_sql_query(query, connection)

display(result)

         country       GDP
0  United States  30500000
1          China  19230000
2        Germany   4744000
3          India   4187000
4          Japan   4180000

In [ ]:
# Part F - Question 12

query = """
SELECT AVG(literacy_rate) AS average_literacy_rate
FROM country_statistics
"""

result = pd.read_sql_query(query, connection)

display(result)

   average_literacy_rate
0                 97.248

In [ ]:
# Part F - Question 13

query = """
SELECT country, literacy_rate
FROM country_statistics
WHERE literacy_rate > 90
"""

result = pd.read_sql_query(query, connection)

display(result)

           country  literacy_rate
0    United States           99.0
1            China           97.2
2            Japan           99.0
3          Germany           99.0
4   United Kingdom           99.0
5           France           99.0
6            Italy           99.0
7           Canada           99.0
8        Australia           99.0
9           Brazil           93.2
10          Russia           99.7
11     South Korea           98.8
12           Spain           98.6
13          Mexico           95.4
14       Indonesia           96.0
15    Saudi Arabia           97.3
16          Turkey           96.7
17    South Africa           95.0
18       Argentina           99.1
19     Netherlands           99.0
20     Switzerland           99.0
21          Sweden           99.0
22          Norway          100.0
23       Singapore           97.5

In [ ]:
# Part F - Question 14

query = """
SELECT country, "Internet Penetration (%)"
FROM country_statistics
ORDER BY "Internet Penetration (%)" DESC
LIMIT 5
"""

result = pd.read_sql_query(query, connection)

display(result)

        country  Internet Penetration (%)
0   Switzerland                     98.21
1        Norway                     97.76
2  Saudi Arabia                     97.66
3        Sweden                     97.55
4   Netherlands                     97.47

In [ ]:
# Part F - Question 15

query = """
SELECT SUM(population) AS total_population
FROM country_statistics
"""

result = pd.read_sql_query(query, connection)

display(result)

   total_population
0        4720039725

In [ ]:
# Part F - Question 16

query = """
SELECT country, "GDP Per Capita"
FROM country_statistics
ORDER BY "GDP Per Capita" DESC
LIMIT 1
"""

result = pd.read_sql_query(query, connection)

display(result)

       country  GDP Per Capita
0  Switzerland            0.11

In [ ]:
# Part F - Question 17

output_path = "/content/merged_country_statistics.csv"

merged_data.to_csv(
    output_path,
    index=False
)

display("CSV file exported successfully.")
display(output_path)

'CSV file exported successfully.'

'/content/merged_country_statistics.csv'

In [ ]:
# Part F - Question 18

query = """
SELECT country, "GDP Per Capita"
FROM country_statistics
ORDER BY "GDP Per Capita" DESC
LIMIT 10
"""

result = pd.read_sql_query(query, connection)

display(result)

          country  GDP Per Capita
0     Switzerland            0.11
1          Norway            0.11
2   United States            0.09
3       Singapore            0.09
4       Australia            0.07
5     Netherlands            0.07
6         Germany            0.06
7  United Kingdom            0.06
8          Canada            0.06
9          Sweden            0.06

In [ ]:
connection.close()

display("Database connection closed.")

NameError: name 'connection' is not defined